name: mdcdalight
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: jonboj <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  js: '^0.6.0'
  logging: '^0.11.3+1'

dev_dependencies:
  test: '^0.12.0'
  browser: '^0.10.0'

#transformers:
# - $dart2js: {checked: true}